version: '3.8'
services:
  autify-app:
    platform: linux/amd64
    build:
      context: ./app
      args:
        HF_API_URL: ${HF_API_URL}
        HF_MODEL_NAME: ${HF_MODEL_NAME}
        HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8000:8000"
